<?xml version="1.0"?>
<package format="3">
  <name>aruco_detect</name>
  <version>0.0.1</version>
  <description>ArUco detector nodes (ROS 2, Python)</description>
  <maintainer email="you@example.com">you</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>image_transport</exec_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <depend>aruco_interfaces</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
